/**
 * 程序主控制器
 */
Ext.define("app.controller.MainController",{
	extend:"Ext.app.Controller",
	mixins: {
		btnCtr:"app.controller.ButtonController",
		formCtr:"app.controller.FormController",
		gridCtr:"app.controller.GridController",
		panelCtr:"app.controller.PanelController",
		queryCtr:"app.controller.QueryController",
		gridActionUtil:"app.util.GridActionUtil",
		suppleUtil:"app.util.SuppleUtil",
		messageUtil:"app.util.MessageUtil",
		formUtil:"app.util.FormUtil",
		sqlUtil:"app.util.SqlUtil",
		queryUtil:"app.util.QueryUtil",
		menuUtils:"app.util.MenuUtil"
	},
	ctr:{},
	init:function(){
		var self=this;
		coreApp=self;
		self.initBtn();
		self.initForm();
		self.initGrid();
		self.initPanel();
		self.initQuery();
		//注册事件
		this.control(self.ctr);
	},
	views:[
		"app.base.BaseGrid",
		"app.base.BaseForm",
		"app.base.BasePanel",
		"app.base.BaseQueryPanel",
		"app.base.BaseCenterPanel"
		]
});